spring.application.name=curd-eg


spring.datasource.username=Vaibhavi
spring.datasource.password=123456

spring.datasource.url=jdbc:h2:mem:dreamtree
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.show.sql=true